
version: "1.0.0"
services:
    frontend:
        build: ./frontend
        ports:
            - "4200:4200"
        volumes:
            - ./frontend:/app
        working_dir: /app
        command: "npm start"
        depends_on:
            - backend
    backend:
        build: ./backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/app
        working_dir: /app
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pollit
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=pollit
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: postgresdb
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=pollit
            - POSTGRES_DB=pollit
