
version: "1"
services:
    app: 
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mariadb
            - PMA_USER=root
            - PMA_PASSWORD=rootpassword
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: postgresdb
        environment:
            - SQL_ROOT_PASSWORD=root
            - SQL_DATABASE=pollit
