version: "3.8"

services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/javascript-node:20
        volumes:
            - .:/workspace:cached
        networks:
            - m347-network
        command: sleep infinity
    frontend:
        image: timmarletaz/frontend:latest
        ports:
            - "4200:4200"
        networks:
            - m347-network
        depends_on:
            - backend

    backend:
        image: timmarletaz/backend:latest
        ports:
            - "8080:8080"
        environment:
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        networks:
            - m347-network
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: postgresdb
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=pollit
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - m347-network

volumes:
    postgres_data:

networks:
    m347-network:
        driver: bridge

