
version: "1.0.0"
services:
    frontend:
        build: ./frontend
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mariadb
            - PMA_USER=root
            - PMA_PASSWORD=rootpassword
        depends_on:
            - db
    backend:
        build: ./backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/app
        working_dir: /app
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: postgresdb
        environment:
            - SQL_ROOT_PASSWORD=root
            - SQL_DATABASE=pollit
