DROP DATABASE IF EXISTS pollit_app;

DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_roles WHERE rolname = 'pollit_user'
        ) THEN
            CREATE ROLE pollit_user LOGIN PASSWORD 'root';
        END IF;
    END
$$;

CREATE DATABASE pollit_app OWNER pollit_user;


-- WICHTIG
-- ZUERST OBEREN TEIL AUSFÜHREN, DANACH IN INTELLIJ MIT DATENBANK VERBINDEN UND ANSCHLIESSEND OBEREN TEIL AUSKOMMENTIEREN,
-- UNTEREN EINKOMMENTIEREN UND ERNEUT AUSFÜHREN


-- \connect pollit_app
--
-- GRANT ALL ON SCHEMA public TO pollit_user;
-- GRANT CREATE ON SCHEMA public TO pollit_user;
--
-- SET ROLE pollit_user;
--
-- CREATE TABLE user_entity (
--                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                              email VARCHAR(255) UNIQUE,
--                              firstname VARCHAR(50),
--                              lastname VARCHAR(50),
--                              password VARCHAR(255),
--                              role VARCHAR(255)
-- );
--
-- CREATE TABLE poll (
--                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                       description VARCHAR(255),
--                       title VARCHAR(255),
--                       uuid VARCHAR(255),
--                       creator_id BIGINT REFERENCES user_entity(id)
-- );
--
-- CREATE TABLE element (
--                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                          is_active BOOLEAN NOT NULL,
--                          label VARCHAR(255),
--                          placeholder VARCHAR(255),
--                          required BOOLEAN NOT NULL,
--                          type VARCHAR(255) CHECK (
--                              type IN (
--                                       'TEXT',
--                                       'CHECKBOX',
--                                       'SLIDER',
--                                       'DATE',
--                                       'EMAIL',
--                                       'NUMBER',
--                                       'INPUT'
--                                  )
--                              ),
--                          poll_id BIGINT REFERENCES poll(id)
-- );
--
-- CREATE TABLE answer (
--                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                         count INTEGER NOT NULL,
--                         value VARCHAR(255),
--                         element_id BIGINT REFERENCES element(id)
-- );
--
-- CREATE TABLE token_entity (
--                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                               created TIMESTAMP,
--                               expires TIMESTAMP,
--                               token VARCHAR(255),
--                               user_id BIGINT REFERENCES user_entity(id)
-- );
--
-- RESET ROLE;
--
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pollit_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pollit_user;
