DROP DATABASE IF EXISTS pollit;
DROP USER IF EXISTS pollit_user;


CREATE USER pollit_user WITH PASSWORD 'root';

CREATE DATABASE pollit OWNER pollit_user;

GRANT CONNECT ON DATABASE pollit TO pollit_user;
GRANT USAGE ON SCHEMA public TO pollit_user;

SET ROLE pollit_user;

CREATE TABLE user_entity
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) CONSTRAINT uk4xad1enskw4j1t2866f7sodrx UNIQUE,
    firstname VARCHAR(50),
    lastname  VARCHAR(50),
    password  VARCHAR(255),
    role      VARCHAR(255)
);

CREATE TABLE poll
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    title       VARCHAR(255),
    uuid        VARCHAR(255),
    creator_id  BIGINT CONSTRAINT fktu8ej340pgf9sbwaobd1u51q REFERENCES user_entity
);

CREATE TABLE element
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_active   BOOLEAN NOT NULL,
    label       VARCHAR(255),
    placeholder VARCHAR(255),
    required    BOOLEAN NOT NULL,
    type        VARCHAR(255)
        CONSTRAINT element_type_check
            CHECK ((type)::TEXT = ANY (
        (ARRAY ['TEXT'::CHARACTER VARYING, 'CHECKBOX'::CHARACTER VARYING,
        'SLIDER'::CHARACTER VARYING, 'DATE'::CHARACTER VARYING,
        'EMAIL'::CHARACTER VARYING, 'NUMBER'::CHARACTER VARYING,
        'INPUT'::CHARACTER VARYING])::TEXT[])),
    poll_id     BIGINT CONSTRAINT fktayorjvf7m1ipngqe9mygek74 REFERENCES poll
);

CREATE TABLE answer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count      INTEGER NOT NULL,
    value      VARCHAR(255),
    element_id BIGINT CONSTRAINT fk5oh2c8ecqaquagcpvkgp59hb1 REFERENCES element
);

CREATE TABLE token_entity
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP(6),
    expires TIMESTAMP(6),
    token   VARCHAR(255),
    user_id BIGINT CONSTRAINT fkchycpasyr16kt66k09e6ompve REFERENCES user_entity
);

RESET ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pollit_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pollit_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pollit_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO pollit_user;

-- Mit postgres DB verbinden in Intellij
-- Ausführen mit Rechtsklick auf datei und dann "init.sql ausführen"
-- DIE DB auswählen und "run"