POST http://localhost:8080/api/polls/create
Content-Type: application/json
token: 468aa365-2169-4d68-a921-4e57e9f60b05

{
  "description": "Test",
  "title": "Umfrage zu Test",
  "elements": [{
    "label": "Test",
    "placeholder": "Test Input",
    "type": "INPUT",
    "required": false
  },
    {
      "required": true,
      "type": "EMAIL",
      "placeholder": "Test",
      "label": "Hallo"
    }
  ]
}

###

GET http://localhost:8080/api/polls/SZPJ9354

###

POST http://localhost:8080/api/polls/SZPJ9354/submit
Content-Type: application/json

{
  "values": ["", "tim@tim.com"]
}

###

GET localhost:8080/api/polls/SZPJ9354/admin
token: 468aa365-2169-4d68-a921-4e57e9f60b05

###

GET localhost:8080/api/polls/SZPJ9354/all/2
token: 468aa365-2169-4d68-a921-4e57e9f60b05

###

GET localhost:8080/api/user/polls/all
token: 468aa365-2169-4d68-a921-4e57e9f60b05
