spring.application.name=pollit
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.max-age=1d
server.servlet.session.cookie.same-site=strict
server.servlet.session.persistent=false